### ISSUE TITLE
add pry as dependency

### ISSUE THREAD

**Issue by bryanwb** [jamie-ci/jamie#7]
since the jamie-console requires it

**Comment by sethvargo** [comment]
:+1:

**Comment by fnichol** [comment]
The console does require it, you're right. I was hoping to keep the pry gem as a "soft" dependency as it isn't strictly needed to make Jamie work (but it is super awesome).

I tried to model its [implementation](https://github.com/jamie-ci/jamie/blob/67586b3622d7330df3a80e02d0c4da8fe36b4f48/lib/jamie/cli.rb#L124-L131) off Bundler's [viz subcommand](https://github.com/carlhuda/bundler/blob/8ea80faba3af9e11513586737d04fa8009699282/lib/bundler/cli.rb#L606-L624).

Does that help with background? I could also start an IRB session and forgo pry altogether. Or fallback to IRB if pry isn't around. Or just add pry :smile: Just a little nervous about adding too many dependencies that could have platform and portability difficulties down the road, despite pry being a pretty good acting gem.

Thoughts?

**Comment by bryanwb** [comment]
u should add it as a dependency

if I do  `jamie --help` , I see jamie console as an option

if I do `jamie console` I get a very confusing stacktrace

if u have jamie console in the --help options, it should work out of the
box imho

if u don't want to have pry as a dependency, i recommend removing console

**Comment by sethvargo** [comment]
Given that pry is superior to irb (and it's relatively small), I +1 just added it as a dep.

**Comment by fnichol** [comment]
Alright, I'm in!
