### ISSUE TITLE
Sane defaults for platforms

### ISSUE THREAD

**Issue by sethvargo** [jamie-ci/jamie#9]
Here's my proposal for shortening the "platforms" section of the `.jamie.yml` file to make it easier for new users.

<table>
  <tr>
    <th>Platform</th>
    <th>Defaults</th>
  </tr>

  <tr>
    <td>ubuntu-12.04</td>
    <td>
<pre>
driver_config:
  box: opscode-ubuntu-12.04
  box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
</pre>
    </td>
  </tr>

  <tr>
    <td>ubuntu-10.04</td>
    <td>
<pre>
driver_config:
  box: opscode-ubuntu-10.04
  box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-10.04.box
</pre>
    </td>
  </tr>

  <tr>
    <td>centos-6.3</td>
    <td>
<pre>
driver_config:
  box: opscode-centos-6.3
  box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
</pre>
    </td>
  </tr>

  <tr>
    <td>centos-5.8</td>
    <td>
<pre>
driver_config:
  box: opscode-centos-5.8
  box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-5.8.box
</pre>
    </td>
  </tr>
</table>

This would allow the `platforms` section of the `.jamie.yml` to be reduced to:

``` yml
platforms:
  - ubuntu-12.04
  - ubuntu-10.04
  - centos-6.3
  - centos-5.8
```

Of course, the verbose configuration options may still be used, but this simplified syntax would be easier to read and quickly add to a community project.

**Comment by portertech** [comment]
Wouldn't this just apply to the vagrant driver?

**Comment by sethvargo** [comment]
Not necessarily. It makes the most sense for the vagrant driver, but if you were using ec2, you could have all the config options in you `.jamie-local.yml`

**Comment by miketheman** [comment]
FYI - CentOS 5.9 is out, thought I should mention.

**Comment by fnichol** [comment]
Currently, the driver subclasses have a `default_config` class method to help setting [default](https://github.com/jamie-ci/jamie-ec2/blob/master/lib/jamie/driver/ec2.rb#L33-L38) configuration attributes (woah).

Currently the value (second argument) is used to populate the config hash, but if a block was permitted the driver could check if its `instance.platform.name` was one of these special default names (the config gets evaluated in the driver's [constructor](https://github.com/jamie-ci/jamie/blob/master/lib/jamie.rb#L1215-L1217)).

So with a little help from Jamie, each driver could choose to use this for default/sane configuration. Sound like a good path forward?

**Comment by sethvargo** [comment]
I think that's the best way to move forward. I just really want to reduce the barrier to entry while retaining all the powerful overrides that already exist.

**Comment by miketheman** [comment]
I think this also assumes 64-arch across the board - might be worthwhile denoting that somewhere.

**Comment by jtimberman** [comment]
FYI, Opscode has updated baseboxes with version 10.18.2.
- https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.8_chef-10.18.2.box
- https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-10.18.2.box
- https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_chef-10.18.2.box
- https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-10.18.2.box

**Comment by sethvargo** [comment]
Joshua, is that published anywhere on the docs/wiki?

**Comment by jtimberman** [comment]
It's published in the bento readme. I don't think we have any information about baseboxes in docs.opscode.com or on the wiki.
